### ISSUE TITLE
Support appending date/text before block ID

### ISSUE THREAD

**Issue by wenlzhang** [ebullient/obsidian-task-collector#10]
With the current version of this plugin, date/text would be appended after block ID, if any:
`- [x] Task ^blockid 2021-10-25`

However, this may break the block ID. Therefore, is it possible to append date/text before the block ID, if any?
`- [x] Task 2021-10-25 ^blockid`

**Comment by wenlzhang** [comment]
With version 0.6.5, I still experience this issue.

**Comment by ebullient** [comment]
Please give me a more concrete example (with text).
Block references should be preserved / remain at the end of the line.
If you can suggest a revision to this test: https://github.com/ebullient/obsidian-task-collector/blob/c745eba2919195c2b3bed186b23eba0bf9520ebb/test/generatedRegExp.test.ts#L189, that would be excellent.

**Comment by wenlzhang** [comment]
I did some tests with different block IDs, and the finding is interesting, as can be seen below.

- With the block ID `^your-id`, as in the test file, it works as expected.
- With the block ID `^ho1nmr`, it does not work.

![CleanShot 2022-01-10 at 14 43 16](https://user-images.githubusercontent.com/44930227/148776404-4060e717-a4bc-4fdc-b9ec-dbd6fe8303c7.gif)

The tests were done with the following conditions:

- The plugin version 0.6.5 was used.
- The block ID was randomly generated by using the following plugin:
  - https://github.com/mgmeyers/obsidian-copy-block-link
  - I frequently use this plugin to generate block IDs.

**Comment by ebullient** [comment]
Thank you! The specific example helps a lot. ;)

**Comment by wenlzhang** [comment]
> I forgot numbers in the regex. 🤦‍♀️

Also, I am not sure if that plugin would generate other symbols in block IDs.

**Comment by ebullient** [comment]
I think, based on Obsidian Help, that we're good: 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/808713/148791408-8d91a75c-81c2-48cf-bd88-60a7652dfdc5.png">

I knew I had to support numbers.. not sure how they didn't end up in the regex. Probably because my test didn't have one!

**Comment by wenlzhang** [comment]
> I think, based on Obsidian Help, that we're good:

That's glad to know!

**Comment by ebullient** [comment]
Ok. Updated in 0.6.6 (which I just pushed, and should be updatable via BRAT).. let me know if I still messed something up! grr. ;)
