### ISSUE TITLE
feat: also move sub bullet points of completed tasks

### ISSUE THREAD

**Issue by dennisseidel** [ebullient/obsidian-task-collector#11]
I plan to add a feature when you move completed tasks that checks if the next line(s) of a completed task are indented & start with a `-`. If that is the cases I would also move those lines. Would you accept such a pull request? 🙂

**Comment by ebullient** [comment]
I believe that works already?

**Comment by dennisseidel** [comment]
I tested it with the following file:

```markdown
- [x] todo 2
	- inline
	- inline2 
- [ ] todo 3

## Log
- [x] todo1
```

what I would have expected was:

```markdown
- [ ] todo 3

## Log
- [x] todo 2
	- inline
	- inline2 
- [x] todo1
```

but currently executing "move all completed task" leads to the following result:

```markdown
	- inline
	- inline2 
- [ ] todo 3

## Log
- [x] todo 2
- [x] todo1
```

**Comment by dennisseidel** [comment]
Ok it looks like a classic: "tabs" vs "spaces" issue 😃 If I use 4 space to indent it works.
