### ISSUE TITLE
At the moment I can use "Mark task" on an existing task, or on a bullet. Is there any reason that it couldn't be extended to a normal (not checkbox or bullet) line?

### ISSUE THREAD

**Issue by ebullient** [ebullient/obsidian-task-collector#113]
At the moment I can use "Mark task" on an existing task, or on a bullet. Is there any reason that it couldn't be extended to a normal (not checkbox or bullet) line? 

I can use "Toggle Checkbox status" to go from a regular line to a checkbox, but it would be more convenient to be able to have an open check box as the first of the task mark cycle and be able to use the same hotkey mapping to progress, whether the line was already a task/bullet or not.

_Originally posted by @RobColes in https://github.com/ebullient/obsidian-task-collector/discussions/107#discussioncomment-4694872_

**Comment by GeorgeGo** [comment]
Yes! I've been looking at this exact feature based on how my flow generally works. I've also realized that I'd like to be able to apply tags to selected tasks in a group and am still on the fence on whether that would fit the scope of task collector. 

I haven't been able to find the specific line that checks for tag status yet but I'd like to submit a pull request when I do, assuming it hasn't already been fixed.

I greatly support the idea.
