### ISSUE TITLE
1.0.3 on Windows - can't find option to clear all checked  checkboxes

### ISSUE THREAD

**Issue by RobColes** [ebullient/obsidian-task-collector#115]
I think clear all checked checkboxes used to be a menu option, and was helpful for periodic tasks I want tick off as I do them, then reset for next time

I can't find it in 1.0.3 in the config - it would be great to have it back.

**Comment by ebullient** [comment]
Was waiting until someone asked for it. ;)

**Comment by RobColes** [comment]
I am that awkward "someone" :-)
