### ISSUE TITLE
Task Collection not working with latest release of Tasks Plugin

### ISSUE THREAD

**Issue by macbikegeek** [ebullient/obsidian-task-collector#127]
Task Collector has worked for me until the latest release of the Tasks plugin. The attached screenshot shows the error I'm getting in the console. Nothing happens when I invoke task collection from the command menu, no doubt due to the error.
![Screenshot 2023-02-01 at 9 47 59 PM](https://user-images.githubusercontent.com/20144822/216218946-1b48d3cf-1a2e-44b8-9a2d-fe0450247e2b.png)

**Comment by claremacrae** [comment]
Does the error happen when Tasks is not enabled?

**Comment by macbikegeek** [comment]
Yes. Not surprising, since as I understand what Task Collector does for Task Collection, it's simply looking at the content in the file and moving task lines around under a completed and a todo header (you get to pick the name) in the note.

**Comment by claremacrae** [comment]
So as far as I can tell, the reference to change in Tasks version may be a red herring?

As I understand it, two people have now said that since they installed the version code in Tasks 1.24.0, TeamCity has stopped working in some way.

Both have said that the problem does not occur when Tasks is disabled.

I am confused by this.

**Comment by macbikegeek** [comment]
interesting, confused as well, since the content of my tasks hasn't changed over the time Task Collection worked to stopped working. And thinking about it, my comment above makes me think more that at least Task Collection shouldn't see anything different. I'm not using custom statuses.

**Comment by ebullient** [comment]
Can you both please encourage folks to open bugs if something doesn't work? I've not been able to keep up w/ discord lately... so this is the first I'm hearing of any problems. Will have a look.

**Comment by ebullient** [comment]
Can you both please encourage folks to open bugs if something doesn't work? I've not been able to keep up w/ discord lately... so this is the first I'm hearing of any problems. Will have a look.

**Comment by claremacrae** [comment]
We do! And it's OK, this has all entirely come from GitHub discussions...

Thanks ever so much for having a look.

**Comment by ebullient** [comment]
ok. I have one follow-up question: 

What sections do you have configured (just #Log?) is only one section defined in the document or did it not exist before you run the collector? (a sanitized version of your file would be excellent).. this is trying to find the "next" header, and this error suggests the header isn't present at all..

**Comment by macbikegeek** [comment]
Here's a note example. Task Collection did not work for this one. Also, screenshots of my Task Collector settings. Thanks for looking into it! 
[Task Entry 2022.md](https://github.com/ebullient/obsidian-task-collector/files/10570624/Task.Entry.2022.md)
![Screenshot 2023-02-02 at 10 42 09 AM](https://user-images.githubusercontent.com/20144822/216371070-480b40eb-f357-4673-bc86-0cd11f213935.png)
![Screenshot 2023-02-02 at 10 41 55 AM](https://user-images.githubusercontent.com/20144822/216371076-08d34d66-0b4c-4d06-b63a-717703082100.png)

**Comment by ebullient** [comment]
Can you give the latest BRAT release a try? (1.0.4)

**Comment by macbikegeek** [comment]
That worked, thanks! I use Live Preview all the time and complete tasks in the Tasks query blocks in Live Preview all the time without any of the issues in 117. Thanks for the quick fix!

**Comment by ebullient** [comment]
I think we fixed this?
