### ISSUE TITLE
option to remove checkboxes when moving them to the archive

### ISSUE THREAD

**Issue by dennisseidel** [ebullient/obsidian-task-collector#13]
I developed a feature that adds an option to: "remove checkboxes from todos that the plugin moves to the archive area". Would that be something you like to include? :)

**Comment by ebullient** [comment]
I would! Just double check the negative lookbehind. Mobile is not straight-up node, and last I attempted, it didn't support them.

**Comment by dennisseidel** [comment]
Thanks for the good hint. Happy to do so :) Any tip on how to test unreleased version on mobil best?

**Comment by ebullient** [comment]
what you could do is make a release on your fork, and point BRAT at the repo..

**Comment by ebullient** [comment]
Delivered in 0.6.3, which is available for beta install using[BRAT](https://github.com/TfTHacker/obsidian42-brat).
