### ISSUE TITLE
Support cancelling tasks with hotkeys

### ISSUE THREAD

**Issue by wenlzhang** [ebullient/obsidian-task-collector#15]
Currently, one can complete tasks with hotkeys and appended text while doing this. It would be great if one can do the same for cancelling tasks, i.e. marking tasks as `[-]` instead of `[x]`.

Also, it would be great if this can be supported in preview mode: https://github.com/ebullient/obsidian-task-collector/issues/8.

**Comment by dariuszkowalski-com** [comment]
+1

**Comment by ebullient** [comment]
There already is a command for cancelling a task that you can absolutely bind to a hotkey (which works in edit/live preview):
<img width="514" alt="image" src="https://user-images.githubusercontent.com/808713/148559503-69835754-f41e-4a66-a21c-684ee47bfaaf.png">

The trouble with preview mode is that you don't have the notion of a current line to issue the command on unless you select text. I was thinking about a right click handler, for that case.

**Comment by wenlzhang** [comment]
I realize that now I do not see the Cancel item command any more with Task Collector version 0.6.1 and Obsidian version 0.13.19. When cancelling tasks with hotkeys, is it also possible to append text?

<img width="751" alt="Screenshot 2022-01-07 at 15 47 37" src="https://user-images.githubusercontent.com/44930227/148560759-e90707d9-2dc5-4ee9-96a9-a3a059e19851.png">

**Comment by ebullient** [comment]
That's very strange. I just pushed 0.6.2, if you want to upgrade, but the screenshot above was taken with 0.6.1 and 0.13.19 .. so I'm not sure what the difference is..

**Comment by wenlzhang** [comment]
> Do you have support for canceled tasks enabled?

Yes, I had it enabled.

With version 0.6.2, I can see the cancel tasks command again. Also, I can use this with hotkeys that append text now. 😃

**Comment by ebullient** [comment]
As of 0.6.3, which is available for beta install using[BRAT](https://github.com/TfTHacker/obsidian42-brat), The commands complete, cancel, or remove _ALL_ items can now be used in preview mode. Those commands that need line context will come next.

**Comment by ebullient** [comment]
As of 0.6.4, which is available for beta install using [BRAT](https://github.com/TfTHacker/obsidian42-brat), a command / right-click menu can be used to complete tasks with an "arbitrary" character (must be either `x`, `X`, ` `, or a character configured in the list of incomplete task values). This command still requires an editor (not reading mode).
