### ISSUE TITLE
Function in preview mode

### ISSUE THREAD

**Issue by kmaustral** [ebullient/obsidian-task-collector#16]
This plug-in works beautifully in edit mode, but it doesn't seem to function in preview. 

Currently, the Task Archiver plug-in and a search and replace templater script can work in preview mode as well as edit.

It would be great to have this function.

**Comment by ebullient** [comment]
As of 0.6.3, which is available for beta install using[BRAT](https://github.com/TfTHacker/obsidian42-brat), The commands complete, cancel, or remove _ALL_ items can now be used in preview mode.

Working on the ones that still require line context will come next.

**Comment by ebullient** [comment]
Delivered in 0.7.0! ✨

**Comment by wenlzhang** [comment]
Can you explain a bit more how to use these features in Preview mode? I tried to complete tasks in Preview mode with version 0.7.1 but it did not work for me.

![CleanShot 2022-01-14 at 10 05 03](https://user-images.githubusercontent.com/44930227/149489050-2a538df2-84ab-44df-b9f4-ccc32736012f.gif)

**Comment by Zebrazilla** [comment]
> Can you explain a bit more how to use these features in Preview mode? I tried to complete tasks in Preview mode with version 0.7.1 but it did not work for me.

Same issue here. Have not gotten it to work. Thought it might have to do with me using Legacy instead of Live Preview, but it works in neither for me.
