### ISSUE TITLE
[Troubleshooting] TC Collects Non-Idented Items Below Tasks

### ISSUE THREAD

**Issue by julroger2013** [ebullient/obsidian-task-collector#161]
Thank you for making this plugin. It really helps to keep tasks organized and out of the way once completed. 

I've noticed what might be a bug. When I collect tasks from my file, the automation grabs not only indented items under a task, which in my view is a desirable behavior, but also list items that are at the _same_ level of indentation as the task. 

For example: 

- [x] Thing 1
    - [ ] Child 1
- [ ] Thing 2
- [ ] Thing 3

In this example, I would expect "Collect tasks" to move "Thing 1" and "Child 1," but not Thing 2 or Thing 3. My experience, however, has been that even non-indented items in a list are collected when they are lower down in the list than a completed task. 

Is this a bug, or an intentional feature of the plugin? My idea was to litter tasks throughout my notes as indented list items, and I had hoped that only the tasks and their children would be moved, not other items in the list. 

Thanks again for designing this plugin! It's very helpful.

**Comment by ebullient** [comment]
Markdown continuation rules get interesting here.. as well as different ideas of what is a task (and subsequent notes).. when some may consider tasks as one-liners. ;)

Markdown format does list continuations like this: 

> To add another element in a list while preserving the continuity of the list, indent the element four spaces or one tab, as shown in the following examples.

```
- [ ] This is the first list item.
- [ ] Here's the second list item.

    A paragraph or text that goes with the second list item.

- [ ] And here's the third list item.
```

I try to ensure that the related text goes with the completed item, as shown in these tests: https://github.com/ebullient/obsidian-task-collector/blob/3171269ed5a13531d8de55a705c0693794f0d00c/test/moveCompletedItem.test.ts#L76

Can you give me a similar example for what you think should or shouldn't be collected?

**Comment by ebullient** [comment]
I added some tests, so I think I found and squashed this. If you still see it, example text helps (before/after)

**Comment by julroger2013** [comment]
Howdy! 

I got around to testing the update this morning. This is almost exactly the functioning that I would have expected, and I'm not certain that the one way in which it differs could be considered a bug -- it might be a preferable function. 

Tasks that are part of a list, but _don't_ have indented content beneath them now collect properly, e.g. "Here is main task No. 1" in the screenshots below. It takes only the task, and none of the other list items below it. 

Tasks that have nested content below them now collect as I would expect, as well, taking all child items with them. That's "Here is main task No. 2" in the screenshots. 

The one function that I might expect to work differently—but again, I'm not sure my expectation is the optimal way of functioning—is where a completed task has nested, uncompleted tasks below it, as in "here is main task No. 3" in the screenshots. I would have expected "main task No. 3" to collect all its children as well, regardless of whether they were completed tasks or not. 
  
![image](https://user-images.githubusercontent.com/94991208/232320852-24ddc3a6-2c3c-438d-9932-e797e091b52f.png)

![image](https://user-images.githubusercontent.com/94991208/232320883-e85d97a8-927f-4f24-911e-dc048ad3c811.png)

Thanks so much for adjusting this! It's now able to be used exactly as I would have wanted -- I just need to make sure to check off subtasks before collecting.

**Comment by ebullient** [comment]
Right.. and that is the tricksy bit. ;) 
I've also just realized I probably have another bug because complete vs. incomplete is a lot more nuanced these days, and I could spread these items across sections! 

So. Here is the question: 
Do I move the whole thing (this could apply to callouts, too), and expect that folks will then pull out and cancel/move/otherwise any items that should go somewhere else? (either before or after)
Should I ever go look for sub-items and move those? or always leave them and only look at top-level parents..
