### ISSUE TITLE
Collect tasks right-click option not shown unless Mark Tasks right-click also selected

### ISSUE THREAD

**Issue by RobColes** [ebullient/obsidian-task-collector#162]
1.0.5, Windows 10. 
I wanted to have the collect tasks on the right click menu but didn't want the mark tasks options to appear.

Selecting "collect tasks" only does not add the collect tasks option to the right-click menu

![Collect Only](https://user-images.githubusercontent.com/1765065/227849317-df0450d4-2980-4f01-aeee-38d9a61ecb6a.png)
![CollectOnlyRight](https://user-images.githubusercontent.com/1765065/227849324-a0a33f93-3a05-4974-8b37-3dc47c6887e9.png)

Selecting Mark tasks and collect tasks correctly shows both sets.
![CollectandMarkRight](https://user-images.githubusercontent.com/1765065/227849323-4c66a331-35f6-4e4f-957e-f03f4665d3ef.png)

**Comment by ebullient** [comment]
Thanks for the report. Will look soon (dev conferences this week & next)
