### ISSUE TITLE
Integrate Task Collector with CSS and Add new types of tasks

### ISSUE THREAD

**Issue by dariuszkowalski-com** [ebullient/obsidian-task-collector#21]
Here:
https://forum.obsidian.md/t/theme-its-dark-light-theme/12838/133

You can find a CSS snippet  for many new Task types:
![image](https://user-images.githubusercontent.com/37656900/148651820-e2a4c7f0-3e1d-41f6-b9c5-03cce5b2f517.png)

Current version of CSS support even more types:
![image](https://user-images.githubusercontent.com/37656900/148651906-53253895-8e3d-4329-a1d2-f3f309df15c0.png)

It would be nice to integrate it with your plugin and add to the plugin other types of tasks and the possibility to add hotkeys for them.

**Comment by ebullient** [comment]
Task Collector doesn't care about any of those kinds of tasks (you can add as many as you wish if you want them to be considered "incomplete".

Are you asking for a similar configuration for complete tasks that could/should be moved?

**Comment by dariuszkowalski-com** [comment]
>There is already a setting for additional values that should be considered incomplete tasks
thx. 


> Are you asking for a similar setting for marking completed tasks?
> Can you describe the workflow you are asking for, please?

Now Your Plugin adds the possibility to assign a Hotkey to Cancel item.
I would like to have separate Hotkeys for every value, which I pun in a mentioned by you form, and is treated as an incomplete task.
Is it possible?

**Comment by ebullient** [comment]
As of 0.6.4, which is available for beta install using [BRAT](https://github.com/TfTHacker/obsidian42-brat), a command / right-click menu can be used to complete tasks with an "arbitrary" character (must be either `x`, `X`, ` `, or a character configured in the list of incomplete task values). This command still requires an editor (not reading mode).

Please see the updated README, and let me know what you think.

**Comment by wenlzhang** [comment]
> As of 0.6.4, which is available for beta install using [BRAT](https://github.com/TfTHacker/obsidian42-brat), a command / right-click menu can be used to complete tasks with an "arbitrary" character (must be either `x`, `X`, ` `, or a character configured in the list of incomplete task values). This command still requires an editor (not reading mode).

I think that @dariuszkowalski-com might mean that it would be great if one can mark incomplete tasks, e.g. `- [ ] Task`, with desired status, e.g. `- [>] Task` and `- [/] Task`, with hotkeys (maybe also append desired text), just like one can complete or cancel incomplete tasks.

**Comment by ebullient** [comment]
Please try 0.6.4. Rather than making a command for each, the "Mark item" command can be assigned to a hot key, and then accepts keystrokes, so you just type the one you want. Making something up: `Cmd-M` then `>` as an example.

**Comment by wenlzhang** [comment]
> Making something up: `Cmd-M` then `>` as an example.

This is interesting! Now that I only see the following three options in the modal, I thought I can only select one from them.

Then it might be useful if one can define desired symbols in the modal, e.g. `[>]`, `[/]`, `[D]`, etc., so that one can select the desired one by clicking it.

Also, with version 0.6.4 I cannot complete tasks any more: https://github.com/ebullient/obsidian-task-collector/issues/24

<img width="188" alt="Screenshot 2022-01-09 at 23 02 10" src="https://user-images.githubusercontent.com/44930227/148702751-2f75adf9-a935-467d-b0df-28a3adf0e0c0.png">

**Comment by ebullient** [comment]
You can already do that. https://github.com/ebullient/obsidian-task-collector#completing-tasks

**Comment by ebullient** [comment]
Given some other early feedback, I'm going to close this, and chase follow-on items separately/specifically.
