### ISSUE TITLE
Complete and cancel tasks do not work any more in version 0.6.4

### ISSUE THREAD

**Issue by wenlzhang** [ebullient/obsidian-task-collector#24]
The only command (among those I tested) that works for me is `Reset task`.

There are no response nor error messages in the console.

**Comment by ebullient** [comment]
ok. I've double checked and all of it works for me. Can you confirm for me: 
1. the configured values you have for tasks (see Incomplete task indicators)
2. what mode you're running in when you try to run the command
3. the exact steps you use for a command: right-click on a task line? right-click while lines are selected?
2. what value is assigned to the task checkbox when you try to reset it?

**Comment by wenlzhang** [comment]
I may have found what caused this issue. In the `data.json` file, the last line, i.e. `"rightClickReset": true`, does not exist when completely re-installing the plugin. Deleting this line makes the plugin works for me again.
```
{
  "completedAreaHeader": "## Completed tasks",
  "removeExpression": "",
  "appendDateFormat": "✅ YYYY-MM-DDTHH:mm",
  "incompleteTaskValues": "",
  "supportCanceledTasks": true,
  "rightClickComplete": true,
  "rightClickMark": true,
  "rightClickMove": false,
  "rightClickResetTask": true,
  "rightClickResetAll": false,
  "rightClickToggleAll": false,
  "completedAreaRemoveCheckbox": false,
  "rightClickReset": true
}
```

**Comment by ebullient** [comment]
Good to know. I'll see what I can do about moving/removing old config. This is good to know. Thanks for trying out the beta. ;)
