### ISSUE TITLE
Support for commenting the completed tasks

### ISSUE THREAD

**Issue by dummifiedme** [ebullient/obsidian-task-collector#25]
A feature request to wrap the tasks in a comment block `%%` or `<!-- -->`.

**Example:**
```md
- [ ] Some task
```
it could be wrapped into %%
```md
%% - [x] Some task %%
```

These would be visible or query-able by dataview and hidden from preview.

**Comment by ebullient** [comment]
You can do this already, actually. Put the %% above, and a few lines below the Completed section header, like this: 
```
%%
## Log


%%
```

Task Collector will ignore the comment indicator, it inserts completed tasks immediately after the specified header.

**Comment by dummifiedme** [comment]
Thanks.
Yes, this is possible, but I was considering it as a way to leave task twinned into the text itself. It helps in noticing when was a particular section was read/studied. Anyway, we can survive with what we have :D
