### ISSUE TITLE
Support for moving tasks in YAML

### ISSUE THREAD

**Issue by dummifiedme** [ebullient/obsidian-task-collector#26]
Some small tasks pertaining to notes could be moved into YAML upon completion and then it would be accessible for listing by dataview, and hidden from the preview at the same time :)

**Example**

```md
---
date: 2022-01-10 13:00
title: this note
tags: 
---

Some note text going on......
- [ ] Some task
- again some text.

```

Could be altered after completion to
```md
---
date: 2022-01-10 13:00
title: this note
tags: 
- [x] Some task
---

Some note text going on......
- again some text.

```

**Comment by ebullient** [comment]
I'm going to close this as a won't fix. It's not a direction I want to attempt. If you have a single task per document workflow, you might be able to get here with some other regex flows.
