### ISSUE TITLE
Support converting list items as tasks and operate on them at the same time

### ISSUE THREAD

**Issue by wenlzhang** [ebullient/obsidian-task-collector#29]
Sometimes, one may want to convert a list item as a task and operate on the transformed task. For instance, one may want to convert the following list item to a task and at the same time complete it and append text at the end. All this can be done by using hotkeys at once, just like what one can do for ordinary tasks.
```
- This is a list item to be converted and completed
```

In short, it would be great if one can manipulate list items in a similar way as tasks, e.g. complete, cancel, mark them.

**Comment by wenlzhang** [comment]
Thanks for the update! While the right-click menu works for me, the hotkeys for completing items do not work for me. I did not see any errors in the console either.

**Comment by ebullient** [comment]
It does work for me, in LP or Edit mode. Are you using the Legacy editor or CM6?

**Comment by wenlzhang** [comment]
I am using CM6, and it does not work for me in either Live Preview or Source Mode.

**Comment by wenlzhang** [comment]
I re-installed version 0.7.1, but it still did not work for me.

**Comment by ebullient** [comment]
Interesting. Can you open a new issue? Tracking things on closed issues is .. not the best plan. ;) I just pushed 0.7.2 to revert a change that was incorrect. Would you please make sure you're now running 0.7.2, and open a new issue with all the versions (what version of Obs, CM5 or CM6, what key binding you tried to set, and what exactly doesn't work).

Make sure you've configured your alternate task values in settings, too. (It will only accept keys that match what is in the modal.. so if the pop-up modal doesn't show the value, nothing will happen when you type it).
