### ISSUE TITLE
Converting list items as tasks and completing them does not work with version 0.7.2

### ISSUE THREAD

**Issue by wenlzhang** [ebullient/obsidian-task-collector#31]
> Interesting. Can you open a new issue? Tracking things on closed issues is .. not the best plan. ;) I just pushed 0.7.2 to revert a change that was incorrect. Would you please make sure you're now running 0.7.2, and open a new issue with all the versions (what version of Obs, CM5 or CM6, what key binding you tried to set, and what exactly doesn't work).

> Make sure you've configured your alternate task values in settings, too. (It will only accept keys that match what is in the modal.. so if the pop-up modal doesn't show the value, nothing will happen when you type it).

_Originally posted by @ebullient in https://github.com/ebullient/obsidian-task-collector/issues/29#issuecomment-1013187835_

Obsidian version 0.13.19 and CM6 are used. The configurations can be seen in the following screenshots, and I tried to Complete and Cancel a list item with hotkeys, but they did not work for me. However, using hotkeys for Marking the list item works.

![CleanShot 2022-01-14 at 16 57 46](https://user-images.githubusercontent.com/44930227/149545773-1bb9ede5-5965-465e-b7ec-4b732f629ba9.gif)
<img width="752" alt="Screenshot 2022-01-14 at 16 53 36" src="https://user-images.githubusercontent.com/44930227/149545809-be1d4495-7334-4b07-bd90-3c6cea966dad.png">

<img width="738" alt="Screenshot 2022-01-14 at 16 53 57" src="https://user-images.githubusercontent.com/44930227/149545837-8d246a87-e441-42f5-98b2-d485e28c8c8a.png">

**Comment by ebullient** [comment]
The above shows working with a plain list item (not a task). 

Marking a plain list item will only work with the Mark command (where you can select the target value of the task after indicating it should indeed be a task).

Complete/Cancel items will only work with task items.

**Comment by ebullient** [comment]
You can do that, using Mark item.
I am tempted to remove the other commands, to be honest. Mark items does all of them much more flexibly. 

For the case you described, you would do exactly what you asked like this (using only fingers on keyboard): 
To make a task and complete it (appending text, etc): `⌘ ⌥ M` (pops up modal) `x`
To make a task and cancel it (appending text, etc): `⌘ ⌥ M` (pops up modal) `-`  
To make a task: `⌘ ⌥ M` (pops up modal) ` `
If you used other custom task values, using `>` as an example:
To defer a task: `⌘ ⌥ M` (pops up modal) `>`

It is much more flexible.

**Comment by wenlzhang** [comment]
Thanks for the detailed explanations!

> Mark item does all of them much more flexibly.

I agree that Mark is more flexible, and it can complete the features of other commands. However, completing tasks/items by using Mark requires two steps, e.g. in the following example.

> To make a task and complete it (appending text, etc): `⌘ ⌥ M` (pops up modal) `x`

On the other hand, completing and cancelling tasks/items and append text are the most frequent use cases for me. Every day, I do this a lot of times. Therefore, being able to achieve these with only one step, e.g. ⌘ ⌥ Enter, instead of two, is very important for me. Therefore, it would be great if completing and cancelling tasks/items can still be supported separately to marking tasks/items.

**Comment by ebullient** [comment]
This is a much clearer explanation! Thank you!

**Comment by wenlzhang** [comment]
> This is a much clearer explanation! Thank you!

Sorry for not being able to explain this more clearly :-(, and thank you for your time and effort on this!

**Comment by ebullient** [comment]
0.7.3 is in flight now, and should sort you out. ;)

**Comment by wenlzhang** [comment]
The hotkeys for completing and cancelling list items work perfectly now!
