### ISSUE TITLE
Support customize the sequences of options for the Mark right-click menu item

### ISSUE THREAD

**Issue by wenlzhang** [ebullient/obsidian-task-collector#32]
I have another picky request. 😅 Since my use case with this plugin would be to mainly complete, cancel and resetting tasks/list items, would it be possible to support customize the features/icons in the Mark right-click menu? This way, one can occasionally Mark tasks/items with the desired status with the Mark menu items.

Currently, I have three statuses set in the configuration pane, i.e. `>/D`. However, there are seven options in total, as can be seen in the screenshot below. Therefore, it would be great if one can completely determine the sequence of these options. For instance, for me, the sequences of the seven options would be `>/DXx- `.

<img width="230" alt="Screenshot 2022-01-14 at 22 18 00" src="https://user-images.githubusercontent.com/44930227/149586678-6424f550-1418-4175-b98a-91692d20adea.png">

**Comment by ebullient** [comment]
So. There is meaning here.

The top row are completed tasks (I'm thinking about how to make those safely customizable, not quite there)

The next row (or rows) are whatever you have for your "additional" tasks, and will be rendered in that order. (space will be added if you didn't include it)

**Comment by wenlzhang** [comment]
Thanks for the explanations!

May I ask how did you customize the icons for those options? If it is through CSS snippets, would you mind sharing them? It looks beautiful.

**Comment by ebullient** [comment]
That is from https://github.com/ebullient/obsidian-theme-ebullientworks

I broke out the tasks snippet, just for you: 
https://github.com/ebullient/obsidian-theme-ebullientworks/blob/main/tasks-snippet.css

=)

**Comment by wenlzhang** [comment]
> I broke out the tasks snippet, just for you

Thank you for this!

I tried to use this snippet combined with the theme Minimal, and the result can be seen in the following screenshot. As can be seen, the defined symbols overlaps with the default check mark symbol, except for ` ` and `/`. It is the same for tasks in Live Preview and Reading View. Could you point out which variable to change to resolve this?

<img width="234" alt="Screenshot 2022-01-15 at 11 47 12" src="https://user-images.githubusercontent.com/44930227/149619383-30ad6c09-d0fa-43c5-91be-2416ba37e8b1.png">

**Comment by ebullient** [comment]
Try adding this to the snippet: 

```
.checklist-plugin-main .group .compact>.toggle .checked,
.is-flashing input[type=checkbox]:checked, input[type=checkbox]:checked {
  background-color: unset !important;
}
```

**Comment by wenlzhang** [comment]
It works perfectly for me now! Thanks for the help!

**Comment by ebullient** [comment]
I'm going to close this.. the customization of completed flags will come in its own time.. but then the ordering for the modal will function similarly to "the rest".
