### ISSUE TITLE
[Feature Request] Notification panel option ON/OFF

### ISSUE THREAD

**Issue by MangoBee** [ebullient/obsidian-task-collector#330]
Hi Developer,

I'm really enjoy your plugin since it gives me a quick toolbar to edit alternative task symbols. There is only slightly minor problem that i cant find where to disable Notification from the plugin. 
I'm very thankful if my request get implemented, that would be quality improvement right there.

Your sincerely,
MangoBee

**Comment by ebullient** [comment]
You should only get notifications when you save settings? Are there others?

**Comment by MangoBee** [comment]
Hi, it always appears when I start the vault. Is that normal?

**Comment by ebullient** [comment]
Hmm. No.. that's too frequent. What does the notification say? (update of settings?) Do you have sync enabled? Have you opened/closed/saved settings? 
(I wonder if you have older settings that are adapted rather than saved..)

**Comment by MangoBee** [comment]
It's the same when you save settings, i see no sync in setting.
![image](https://github.com/ebullient/obsidian-task-collector/assets/105246494/b4f1a71e-7bd1-45be-adff-149a71e6d511)

**Comment by ebullient** [comment]
Right. After you save it once, and you restart.. it happens again?

**Comment by ebullient** [comment]
It will happen on exit from settings (or if you push save button). Should not happen at startup, unless something is restoring old settings.

**Comment by MangoBee** [comment]
Hi again, sofar im really enjoying using your plugin, it enables for my daily workflow much easier, big thanks. 
About the problem that I stated before. I accidentally found the cause. Its "Settings Search"-plugin, just so you know.
