### ISSUE TITLE
Click handling on checkbox not working in Live Preview

### ISSUE THREAD

**Issue by bodydiv** [ebullient/obsidian-task-collector#348]
Click handling directly on checkboxes doesn't work in Live Preview mode, but it does work in Reading mode.

https://github.com/ebullient/obsidian-task-collector/assets/17952264/9fce3eff-92be-4be6-8f67-b9e96836f679

Obsidian v1.4.16
TC v1.0.13

TC is the only Community Plugin I have enabled.

**Comment by ebullient** [comment]
This is the hardest to debug. I will ask for a few things: 
1) restart obsidian after you change that particular toggle to make sure handlers are registered.
2) Close and re-open that particular note to ensure the contents are re-rendered (and event handlers are attached)

There is a debug setting, but it is pretty noisy. It will at least show you if Task Collector is attempting to register handler events in LP mode
