### ISSUE TITLE
[BUG] Completion date not replaced correctly

### ISSUE THREAD

**Issue by dummifiedme** [ebullient/obsidian-task-collector#35]
![image](https://user-images.githubusercontent.com/68785729/150700716-b967e685-93ec-40fe-b67e-7795a024bf10.png)
![image](https://user-images.githubusercontent.com/68785729/150700722-1a07f44c-31bd-4093-979f-d9cbdb1ecb44.png)

**Comment by ebullient** [comment]
Ok. The append string should be specified in the proper format for moment (which includes literal text in braces, confusingly including literal braces).

For the dataview string you want, that value should be: `[[completion:: ]YYYY-MM-DD[]]`
