### ISSUE TITLE
Support appending text when marking tasks

### ISSUE THREAD

**Issue by wenlzhang** [ebullient/obsidian-task-collector#36]
It would be great if one can append text when marking tasks, just like what one can do when completing and cancelling tasks.

Also, it would be great if one can set the appended text to be different from those for completing and cancelling tasks. After all, after completing/cancelling tasks, one may not need to follow up with the task any more. When marking tasks, however, e.g. marked it as `[/]`, one may still need to follow up with such tasks. This way, one can query different types of tasks by looking for different types of appended text.

**Comment by ebullient** [comment]
This one is a little tricky.

Annotating the same way (e.g. with a simple date) could be doable with a simple option (and undo/reset could still work, in that case). Annotation with different strings is a different animal, as it then becomes difficult to know what strings to look for or remove if you then change the state to a different value. It isn't impossible, but it is way easier to fubar. ;)

When I do this, I use the task collector to mark the task w/ the special character, but I add the tags or follow-up indicator myself (as it isn't often that consistent.. delegation can be easy enough, but follow-up/check-later would be really difficult to automate consistently, at least as I do things... )

**Comment by wenlzhang** [comment]
> Annotation with different strings is a different animal, as it then becomes difficult to know what strings to look for or remove if you then change the state to a different value.

How about only keep the text corresponding to the latest status of the task then? For example, when the status of the task changes in the following manners, only the text/date correspond to the current status is kept. This also means that whenever the status of a task is changed, the original text would be first removed and then the new text would be appended.
```
- [ ] Task
- [>] Task 2022-02-07T12:00
- [/] Task 2022-02-08T12:00
- [x] Task 2022-02-09T12:00
```

Of course, one can manually copy the text corresponding to the previous status of the task and save it as a sub-list item, for example, if one wants.

This way of handing the appended text corresponding to the status of the task also prevents the task description from being too long, if the status changes a few times.

**Comment by ebullient** [comment]
Exactly. Applying the configured append string all of the time is doable (as I already know how to undo that to allow a new value to be set), and yes, could be toggled via config.
