### ISSUE TITLE
Multiple ## Log for completed Tasks in a page

### ISSUE THREAD

**Issue by kngautham** [ebullient/obsidian-task-collector#38]
Option to have multiple ## Logs to collect completed Tasks.

If there are multiple ## Logs in a document, Completed Tasks should go to the nearest ## Log.

Would be very useful

**Comment by ebullient** [comment]
That's an interesting idea.

**Comment by ebullient** [comment]
This is included in 1.0.x (BRAT release ATM)

**Comment by kngautham** [comment]
Thanks for the update, Great work
