### ISSUE TITLE
Select the whole line on right click

### ISSUE THREAD

**Issue by Nemoos-0** [ebullient/obsidian-task-collector#40]
When selecting a piece of text and right-clicking on it, the text after the selection get selected 'til the end of the line.
I tried turning off the plugin and this behavior disappeared, so I think it is the problem.

By the way, thanks for the awesome plugin.

**Comment by ebullient** [comment]
THANK YOU for pointing that out! I noticed the same behavior, but hadn't connected it to my plugin! Aces!
