### ISSUE TITLE
Recurring tasks "on complete"

### ISSUE THREAD

**Issue by WyldKard** [ebullient/obsidian-task-collector#42]
Is there a way to configure a recurring task to set the next date based on the day it was completed, not based on the day it was due? In other words, how would one configure a task to repeat "X days after the completion date"?

The "in X days" method seems to repeat the task X days after the day the completed task was due, which is not what I want.

Thanks!

**Comment by ebullient** [comment]
The Task Collector plugin does not do anything with recurring tasks (or otherwise). I think you have your task plugins confused. ;)

**Comment by WyldKard** [comment]
Sorry, I did. Thanks!
