### ISSUE TITLE
Items do not have proper icons 

### ISSUE THREAD

**Issue by Luvideria** [ebullient/obsidian-task-collector#476]
### Input data (markdown source)

I'm trying to make a todo list look good.
I've seen the issue being raised in the discussion section but if it happens to me too, then it's bound to happen to others.
I have the default theme.

### Expected Behavior

Reloaded the plugin, turned off and on again, quit obsidian and tried again, also in a vault with only this plugin (it was the only one anyway)
All the icons look the same to me. 
I expected icons to look as they do on the plugin images

### Current behaviour

![image](https://github.com/ebullient/obsidian-task-collector/assets/40994907/cfe18c65-dd97-48ad-9d05-4c770c9d8e1b)

### Steps to reproduce

just create a bunch of todos with different letters configured

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version

1.5.12

### Tasks Plugin Version

1.0.17

### Checks

- [X] I have tried it in the sandbox vault with only this plugin enabled

**Comment by ebullient** [comment]
You're missing a snippet. Icons are styled by your theme, not by the plugin itself.

Ebullientworks has a snippet
ITS theme has a snippet
You can use the snippetor plugin to create your own snippet (and then remove it)
