### ISSUE TITLE
Support tasks within callouts

### ISSUE THREAD

**Issue by corinnekaryiu** [ebullient/obsidian-task-collector#48]
Currently I am unable to use Task Collector if a task sits within a callout, for example:

```
> [!todo] Tasks
> - [ ] Task
```

It would be great if these tasks could be supported.

**Comment by ebullient** [comment]
oh weird.. I'll look

**Comment by ebullient** [comment]
In the case where completed items are moved, would you expect them to be removed from the callout? (leading `> ` stripped?)

**Comment by corinnekaryiu** [comment]
Hmm, I don't actually use that option, so I can't really answer that. If I was to, I think I'd be quite happy for them to move into a normal non-callout list, but others might have a different set-up.

Thanks for looking into this!

**Comment by ebullient** [comment]
Try with latest BRAT release (0.7.8) .. and let me know

**Comment by corinnekaryiu** [comment]
Perfect - it works now! Thank you 🙂
