### ISSUE TITLE
Allow only [x] not [X]

### ISSUE THREAD

**Issue by Ampa** [ebullient/obsidian-task-collector#49]
I really dislike the look of a capital X in completed checkboxes.

Could you add the option to only suggest a lower case x, rather than show both in the right click context menu?

It would also save space in the menu!

**Comment by ebullient** [comment]
Try with latest BRAT release (0.7.8) .. and let me know

**Comment by Ampa** [comment]
So quick! Awesome! Thank you so much. 

I almost thought it was a silly request and didn't ask, but immediately I like the plugin better.
