### ISSUE TITLE
Checklists starting with * aren't marked

### ISSUE THREAD

**Issue by Twiglet1022** [ebullient/obsidian-task-collector#491]
### Input data (markdown source)

```
* [ ] A
* [ ] B
````

### Expected Behavior

1. Enable click handling in the Task Collector settings
2. Click on a check box
3. Select an option
4. Checklist item will be marked

### Current behaviour

1. Enable click handling in the Task Collector settings
2. Click on a check box
3. Select an option
4. Nothing happens

### Steps to reproduce

1. Copy the example markdown in a new sandbox vault.
2. Install the Task Collector plugin and enable click handling in the settings.
3. Try to mark a task using the pop up. Nothing will happen, regardless of whether you use the keyboard or mouse.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.6.5

### Tasks Plugin Version

1.0.17

### Checks

- [X] I have tried it in the sandbox vault with only this plugin enabled

**Comment by ShreyaPatibanda** [comment]
Should Be Resolved
