### ISSUE TITLE
✨ Allow prompt on right click of checkbox

### ISSUE THREAD

**Issue by LandonSchropp** [ebullient/obsidian-task-collector#544]
### 🔖 Feature description

When checking items on my list, by far the most common scenario is to use a standard `x`. Because of this, I'd love an easy way to open the prompt while still preserving the normal click behavior.

### ✔️ Solution

I think a good way to do this would be to add an option to open the prompt when _right_ clicking the menu. It's essentially work exactly the same as this option, but just with a right click instead.

![Screenshot 2024-09-21 at 2 14 46 PM](https://github.com/user-attachments/assets/9639ce37-5480-4bcd-8b49-84568ffb492f)

### ❓ Alternatives

Another alternative would be to show the prompt when clicking and _holding_ on the checkbox. Since there's no right click on mobile, this would work better there.

To be honest, I'd love _both_ behaviors, so I could use right clicks on my laptop and holds for my phone.

### 📝 Additional Context

Thank you for creating this great plugin!

**Comment by ebullient** [comment]
Right click already works this way in reading/live preview mode.

In edit mode, right-click is reserved for the context menu, and I am not going to disrupt/change that.

In edit mode, I use keyboard commands: Ctrl-Enter for standard check/uncheck, Shift-Ctrl-Enter for the modal. On Mobile, I use the Task Collector modal always.

If you have "simple vs. complex" operations, you could consider defining two different completion groups. Keep `-` and `x` in a simple group (no date, no text manipulation, but still treat that group as "completed" items). And add another group that uses `X` (as a completed item), that also includes the date, etc. 

Modal would then work (put task collector in the mobile button bar) and you can choose the non-fancy simple x version or the fancier/labeled X

**Comment by LandonSchropp** [comment]
Fair enough. Thanks for considering the request. 🙂
