### ISSUE TITLE
Append date when marking <

### ISSUE THREAD

**Issue by imeed166** [ebullient/obsidian-task-collector#56]
Inspired by this [issue](https://github.com/ebullient/obsidian-task-collector/issues/36), could we get a prompt whenever we mark a task with `>` to write a date (preferably in natural language) then append it to the task in this dataview supported format `[due: YYYY-MM-DD]` ?

This will be especially useful when it'll be possible to mark task [right from the dataview query](https://github.com/ebullient/obsidian-task-collector/issues/43).

**Comment by ebullient** [comment]
How do you see this working? 
- always prompt? 
- Only prompt sometimes? 
- Or .. only prompt when delegating? This could require/recommend a specific text append/replacement string per type, which gets interesting...

**Comment by imeed166** [comment]
In my case, always prompt but only when marking with `>`. I don't need a prompt for the other types.

**Comment by imeed166** [comment]
Sorry, I meant a prompt the `< : schedulling` type, not `> : forwarded`

![image](https://user-images.githubusercontent.com/38974541/169668100-989650d4-23bf-448d-8883-a976297213fe.png)

**Comment by ironfroggy** [comment]
Could this be generalized to expand the "Additional task types" setting to a list of each type where each item can be given a character, text to append when marking (rolling "Append to completed task" into this task type list), or leaving that field blank if a type shouldn't get marked.

**Comment by ebullient** [comment]
This is in flight right now.

**Comment by ebullient** [comment]
This will be done in 1.0.x (already present in BRAT release).
