### ISSUE TITLE
Bug: Preview Mode right click handler not working

### ISSUE THREAD

**Issue by Zebrazilla** [ebullient/obsidian-task-collector#57]
I can not get the preview mode right-click handler to work, which was added in https://github.com/ebullient/obsidian-task-collector/pull/27, same issue as was reported in https://github.com/ebullient/obsidian-task-collector/issues/16#issuecomment-1012936323

Are we doing something wrong or did something break?

> ![CleanShot 2022-01-14 at 10 05 03](https://user-images.githubusercontent.com/44930227/149489050-2a538df2-84ab-44df-b9f4-ccc32736012f.gif) [ ](https://user-images.githubusercontent.com/44930227/149489050-2a538df2-84ab-44df-b9f4-ccc32736012f.gif)

**Comment by ebullient** [comment]
Something may have broken.. there have been some CSS changes.

**Comment by Zebrazilla** [comment]
> Something may have broken.. there have been some CSS changes. Are you on the Insider build? (0.15.+)?

I am still on latest public release, 0.14.15.

**Comment by Zebrazilla** [comment]
I just tried a brand new vault in 0.14.15 with no additional plugins other than TC. Right-click menu is not appearing in Preview mode, neither in Legacy Preview mode nor in Live Preview mode.

**Comment by ebullient** [comment]
Thanks for confirming

**Comment by ebullient** [comment]
Ok. I've had some time to work with it, and it does work for me.

Did you enable it? 
<img width="772" alt="image" src="https://user-images.githubusercontent.com/808713/178147464-393c2733-9fa2-4182-99b8-2f2a7432cc3f.png">

You can also bind the command (applies to edit mode): 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/808713/178147501-54d7e475-cdda-463d-983a-cedbd689d517.png">

This doesn't yet work for dataview tasks in reading mode, I have some work to do with the beta version to help with that.

**Comment by ebullient** [comment]
Are you seeing this on a mobile device, by chance?

**Comment by ebullient** [comment]
This works in 0.15.*, and is also working in 0.16. Make sure you have the right-click menu enabled. Note the command binding only works for live preview or source mode (as it requires active selection of current line.
