### ISSUE TITLE
Clicking Enter/Return at end of line with non-standard state falls back to unordered list

### ISSUE THREAD

**Issue by danielskowronski** [ebullient/obsidian-task-collector#60]
When you click Enter/Return key at the end of a line with non-standard state (e.g. `-`) the new line is not a checkbox line - rather it is a regular unordered list item. For standard states that are handled by Obsidian itself, it works like expected - new line is of the same type as previous one.

---

Current behaviour:

```markdown
- [-] item 1 ⏎
```
produces:
```markdown
- [-] item 1
- ...
```

Expected behaviour:

```markdown
- [-] item 1 ⏎
```
produces:
```markdown
- [-] item 1
- [ ] ...
```

**Comment by ebullient** [comment]
hmm. I am not sure this is something I can fix. Have you raised it in Obsidian forum?

**Comment by danielskowronski** [comment]
Not yet - and I just identified it is not an issue with TaskCollector or Obsidian - rather other community plugin (Outliner) does not handle custom task statuses properly.

I think it is example of how we need some proper testing system for such issues in Obsidian plugins community ;)
