### ISSUE TITLE
[Feature Request]: Ignore Section(s) when Moving Completed Tasks

### ISSUE THREAD

**Issue by benshead** [ebullient/obsidian-task-collector#67]
I am loving Task Collector! It strikes the perfect balance between automating my task management and allowing me to keep the manual processes that help me stay focused on my tasks. Thank you so much for developing it!

## Feature Description
I would like the ability to identify certain sections (such as "## Daily Exercises") in my Daily File for TC to ignore when moving completed tasks. This would help me keep my archived daily files organized.

Thanks for everything!

**Comment by ebullient** [comment]
Question on this one...

Would you want the section all the way through (`## 2nd-level heading 1` through `## 2nd-level heading 2` or `---` or end of document), or to the next heading/hr (`## 2nd-level heading 1` through `### Nested heading` or `### 2nd-level heading 2` or `---` or end of document).

**Comment by benshead** [comment]
Thanks for looking into this! The first option (where sub-heads under the skipped section would also be skipped) would work perfectly for me.

Still really enjoying TC. Thanks for it!

**Comment by sigrunixia** [comment]
I have an alternative option, skipped sections could be defined by a specific marker. Such as an emoji icon, a keyword, or some other defined value within that section. That way all possible use cases could be be covered by such a feature.

**Comment by ebullient** [comment]
Question still stands... start/stop? one section to the next same level section?

**Comment by sigrunixia** [comment]
In my own case, I use many varying levels of headers for not only their prettiness of colors and contrast, but because the data tends to subset itself in such a way. Box 3 of your question would work best in my case, which is why I suggested that specific sections be defined as skip and then you would not have to hard code for every possible use case that comes up.

**Comment by ebullient** [comment]
OH! yes. I see what you mean.
