### ISSUE TITLE
After upgrade on default theme all the icons/commands work just as a standard checkbox

### ISSUE THREAD

**Issue by igormoochnick** [ebullient/obsidian-task-collector#68]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/1222369/199336523-ff198710-12cf-4635-90a6-c4716731dbe2.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/1222369/199336584-1e31312f-8106-4187-a5b9-1b890e2bf5de.png">

**Comment by ebullient** [comment]
You will need to update the snippet you were using to render checkboxes. 1.0 significantly changed the styling for tasks. [Snippetor](https://github.com/ebullient/obsidian-snippetor) has been updated to produce snippets for 1.0.

As a first pass, you could try one of these: 

- [Ebullientworks](https://raw.githubusercontent.com/ebullient/obsidian-theme-ebullientworks/main/tasks-snippet.css)
- [ITS Theme checkboxes](https://raw.githubusercontent.com/SlRvb/Obsidian--ITS-Theme/main/Snippets/S%20-%20Checkboxes.css)

**Comment by ebullient** [comment]
Did this resolve your issue?
