### ISSUE TITLE
support for deleting completed tasks

### ISSUE THREAD

**Issue by imeed166** [ebullient/obsidian-task-collector#7]
It would be nice if we could set a maximum number of completed tasks, and if the number of completed tasks exceeds it, the other tasks would automatically be deleted. And of course, if the number is set to "0", then all the tasks completed are deleted automatically.

**Comment by ebullient** [comment]
This plugin never deletes tasks, and, TBH, that's a level of potential information loss I don't want to get near.
Do you mean complete/cancel the rest? 

Can you be a little more specific about the workflow you would like, given it has to work well with other kinds of docs that don't support this workflow?

**Comment by ebullient** [comment]
That helps. Would this work for you?
https://www.reddit.com/r/ObsidianMD/comments/q1fhsw/archiving_tasks/

**Comment by imeed166** [comment]
> I think it works for a selection.. (select many lines.. )

Yes but completed tasks are mixed with ongoing tasks so I can't select them all at once
> It might be that a combination of both works... my plugin would move them all to the bottom, which would make them easier to bulk select?

As you said, I have to use your plugin to move them to the bottom, but then how do I bulk select and delete them automatically ?

**Comment by imeed166** [comment]
I still have to manually apply ruleset. I was thinking something similar to the setting found in kanban plugin :

![image](https://user-images.githubusercontent.com/38974541/136830786-e4ec91ca-ed50-4ebd-be97-0cc663b6bdc2.png)

**Comment by kmaustral** [comment]
Has there been any progress on this? I'd like to reset checklist tasks, but I would need to delete older completed tasks beforehand.

**Comment by ebullient** [comment]
I prefer my plugin to remain non-destructive to avoid data loss. Deleting lines is not something I want to do accidentally. This flow (for me) is about archival within a document where completed tasks have context that I still want to refer to later.

What I would suggest (if you're game) is to try the https://github.com/No3371/obsidian-regex-pipeline plugin.

Your index.txt file can reference another file called "removeCompletedTasks" (or whatever you like).

removeCompletedTasks should contain something like: 
```
"^- \[x\] .*\n"->"Replace completed task (including newline)"x
```
If you want to add other conditions (to only remove tasks that follow a certain pattern), that would be doable. You could also add the follow-on bulk reset here, if they should go together.

Of course, this approach won't work if you only want to reset tasks in a specific section, in which case, I guess I should be more accommodating.

**Comment by kmaustral** [comment]
A way of limiting task reset to a specific section would be even better.

**Comment by ebullient** [comment]
There is another way to do this, I've realized. An option already exists to "delete" the checkbox (make it not a task anymore). I may update this to allow "replace the completed checkbox with another character", which would allow any task type to be replaced, and would allow me to reverse/reset them.

As far as removing/deleting lines completely, I still feel this is better done/automated with regex pipelines.

@kmaustral .. can you open a separate issue for resetting tasks within a certain section?

**Comment by ebullient** [comment]
for regex pipelines plugin, I use these...

1) to "remove" a checkbox by transforming it to some other character: 

```
"^(\s*)- \[x\]"->"$1- ✔️"
"^(\s*)- \[r\]"->"$1- 👀"
"^(\s*)- \[R\]"->"$1- 👀"
"^(\s*)- \[\/\]"->"$1- 🔛"
"^(\s*)- \[>\]"->"$1- 🔜"
"^(\s*)- \[-\]\s+(.*)$"->"$1- 〰️ ~~$2~~"
```

2) to delete a checkbox line entirely (I'm deleting generic lines from day planner agenda:

```
"^- \[[x ]\] \d+:\d+ Start[ :]*\n"->"Generic block"x
"^- \[[x ]\] \d+:\d+ .*GH Notifications / Email\n"->"Generic morning"x
"^- \[[x ]\] \d+:\d+ BREAK / (Sudo|chat)\n"->"Generic break"x
"^- \[[x ]\] \d+:\d+ Meeting / email\n"->"Generic meeting"x
"^- \[[x ]\] \d+:\d+ Meditation *\n"->"Generic meditation"x
"^- \[[x ]\] \d+:\d+ (Lunch|Email|Reflection|Preview tomorrow's Agenda)\n"->"Generic blocks"x
"^- \[[x ]\] \d+:\d+ END.*\n"->"Allow meal block"x
```
