### ISSUE TITLE
Is it possible to append date/text in preview mode?

### ISSUE THREAD

**Issue by wenlzhang** [ebullient/obsidian-task-collector#8]
It would be great if one can complete tasks and append date/text in preview mode. For instance, this may work as follows:

- One presses hotkeys like `Cmd` and left clicks a task to complete it
- This plugin automatically appends date/text to the completed task

**Comment by wenlzhang** [comment]
As mentioned in the following Dataview discussion, it would be great if Task Collector can be somewhat integrated with Dataview. For instance, one can complete/reset tasks in preview mode and append/remove text/timestamp accordingly.
https://github.com/blacksmithgu/obsidian-dataview/discussions/681

**Comment by ebullient** [comment]
I believe you should already be able to do this if you set the text around the appended date to match what dataview produces.

**Comment by wenlzhang** [comment]
> I believe you should already be able to do this if you set the text around the appended date to match what dataview produces.

Please see the reply at https://github.com/blacksmithgu/obsidian-dataview/discussions/681#discussioncomment-1925851.

**Comment by ebullient** [comment]
Going to close this one to consolidate with #16 (as we've had a different discussion in this one re: dataview compatibility).
